name: Flask-Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Docker Login
      - name: Docker Login 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      # Step 3: Build and push Docker image
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag cptr9/flaskui:1.0
          docker push cptr9/flaskui:1.0
